dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.0
  - smartcontractkit/chainlink-brownie-contracts@0.3.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.0'
reports:
  exclude_contracts:
    - LinkToken
    - VRFCoordinatorMock
    - ERC721
    - EnumerableMap
    - Address
    - EnumerableSet
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  default: rinkeby
  rinkeby:
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    fee: 100000000000000000

  mainnet-fork:
    link_token: '0x514910771AF9Ca656af840dff83E8264EcF986CA'
    vrf_coordinator: '0xf0d54349aDdcf704F77AE15b96510dEA15cb7952'
    keyhash: '0xAA77729D3466CA35AE8D28B3BBAC7CC36A5031EFDC430821C02BC31A238AF445'
    fee: 100000000000000000
upload_ipfs: false
